### ISSUE TITLE
nohup挂后台会失败

### ISSUE THREAD

**Issue by louis26wq** [Soulter/AstrBot#141]
前台运行正常。
使用nohup python3 -u main.py > test.log 2>&1 &

[32;49m[12-16 23:56:36] [INFO] [System]: 🎉 项目启动完成。[0m
>>> Exception in thread Thread-1 (main):
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/root/qqchangpt/AstrBot/main.py", line 48, in main
    qqBot.initBot(cfg, provider)
  File "/root/qqchangpt/AstrBot/cores/qqbot/core.py", line 426, in initBot
    asyncio.get_event_loop().run_until_complete(cli())
  File "/usr/local/python3/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/qqchangpt/AstrBot/cores/qqbot/core.py", line 434, in cli
    prompt = input(">>> ")
             ^^^^^^^^^^^^^
OSError: [Errno 9] 错误的文件描述符

**Comment by Soulter** [comment]
hello，近期我会推一版支持可视化界面的版本，这个版本将会解决你提到的问题。

**Comment by Soulter** [comment]
已修复
