### ISSUE TITLE
[Bug] 拉取最新源码后，无法启动

### ISSUE THREAD

**Issue by Mushan3420** [Soulter/AstrBot#222]
### 发生了什么

拉取最新源码后，启动报错如下：
`Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 98, in <module>
    asyncio.run(core_lifecycle.initialize())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/core_lifecycle.py", line 38, in initialize
    self.platform_manager = PlatformManager(self.astrbot_config, self.event_queue)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/platform/manager.py", line 21, in __init__
    match platform['type']:
          ~~~~~~~~^^^^^^^^
KeyError: 'type'`

尝试完全删除，按文档使用源码部署，又报错如下：
`Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 8, in <module>
    from astrbot.core.core_lifecycle import AstrBotCoreLifecycle
  File "/www/wwwroot/AstrBot/astrbot/__init__.py", line 1, in <module>
    from .core.log import LogManager
  File "/www/wwwroot/AstrBot/astrbot/core/__init__.py", line 8, in <module>
    db_helper = SQLiteDatabase(DB_PATH)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 23, in __init__
    self.conn = self._get_conn(self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 29, in _get_conn
    conn = sqlite3.connect(self.db_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
(venv) ecs-user@iZ2ze6vc1a9sydwysuq7mzZ:/www/wwwroot/AstrBot$ venv/bin/python3 main.py
Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 8, in <module>
    from astrbot.core.core_lifecycle import AstrBotCoreLifecycle
  File "/www/wwwroot/AstrBot/astrbot/__init__.py", line 1, in <module>
    from .core.log import LogManager
  File "/www/wwwroot/AstrBot/astrbot/core/__init__.py", line 8, in <module>
    db_helper = SQLiteDatabase(DB_PATH)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 23, in __init__
    self.conn = self._get_conn(self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 29, in _get_conn
    conn = sqlite3.connect(self.db_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
(venv) ecs-user@iZ2ze6vc1a9sydwysuq7mzZ:/www/wwwroot/AstrBot$ python3 main.py
Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 8, in <module>
    from astrbot.core.core_lifecycle import AstrBotCoreLifecycle
  File "/www/wwwroot/AstrBot/astrbot/__init__.py", line 1, in <module>
    from .core.log import LogManager
  File "/www/wwwroot/AstrBot/astrbot/core/__init__.py", line 8, in <module>
    db_helper = SQLiteDatabase(DB_PATH)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 23, in __init__
    self.conn = self._get_conn(self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 29, in _get_conn
    conn = sqlite3.connect(self.db_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
(venv) ecs-user@iZ2ze6vc1a9sydwysuq7mzZ:/www/wwwroot/AstrBot$ sudo venv/bin/python3 main.py
Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 8, in <module>
    from astrbot.core.core_lifecycle import AstrBotCoreLifecycle
  File "/www/wwwroot/AstrBot/astrbot/__init__.py", line 1, in <module>
    from .core.log import LogManager
  File "/www/wwwroot/AstrBot/astrbot/core/__init__.py", line 8, in <module>
    db_helper = SQLiteDatabase(DB_PATH)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 23, in __init__
    self.conn = self._get_conn(self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 29, in _get_conn
    conn = sqlite3.connect(self.db_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
(venv) ecs-user@iZ2ze6vc1a9sydwysuq7mzZ:/www/wwwroot/AstrBot$ sudo ./venv/bin/python3 main.py
Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 8, in <module>
    from astrbot.core.core_lifecycle import AstrBotCoreLifecycle
  File "/www/wwwroot/AstrBot/astrbot/__init__.py", line 1, in <module>
    from .core.log import LogManager
  File "/www/wwwroot/AstrBot/astrbot/core/__init__.py", line 8, in <module>
    db_helper = SQLiteDatabase(DB_PATH)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 23, in __init__
    self.conn = self._get_conn(self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 29, in _get_conn
    conn = sqlite3.connect(self.db_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file`

### 如何复现？

1. 拉取最新源码 git pull
2. 重新启动项目 python3 main.py

### AstrBot 版本与部署方式

3.4.0 手动部署 Ubuntu 24.04 LTS Python 3.12.3

### 操作系统

Linux

### 额外信息

`Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 98, in <module>
    asyncio.run(core_lifecycle.initialize())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/core_lifecycle.py", line 38, in initialize
    self.platform_manager = PlatformManager(self.astrbot_config, self.event_queue)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/platform/manager.py", line 21, in __init__
    match platform['type']:
          ~~~~~~~~^^^^^^^^
KeyError: 'type'`

`Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 8, in <module>
    from astrbot.core.core_lifecycle import AstrBotCoreLifecycle
  File "/www/wwwroot/AstrBot/astrbot/__init__.py", line 1, in <module>
    from .core.log import LogManager
  File "/www/wwwroot/AstrBot/astrbot/core/__init__.py", line 8, in <module>
    db_helper = SQLiteDatabase(DB_PATH)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 23, in __init__
    self.conn = self._get_conn(self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 29, in _get_conn
    conn = sqlite3.connect(self.db_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
(venv) ecs-user@iZ2ze6vc1a9sydwysuq7mzZ:/www/wwwroot/AstrBot$ venv/bin/python3 main.py
Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 8, in <module>
    from astrbot.core.core_lifecycle import AstrBotCoreLifecycle
  File "/www/wwwroot/AstrBot/astrbot/__init__.py", line 1, in <module>
    from .core.log import LogManager
  File "/www/wwwroot/AstrBot/astrbot/core/__init__.py", line 8, in <module>
    db_helper = SQLiteDatabase(DB_PATH)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 23, in __init__
    self.conn = self._get_conn(self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 29, in _get_conn
    conn = sqlite3.connect(self.db_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
(venv) ecs-user@iZ2ze6vc1a9sydwysuq7mzZ:/www/wwwroot/AstrBot$ python3 main.py
Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 8, in <module>
    from astrbot.core.core_lifecycle import AstrBotCoreLifecycle
  File "/www/wwwroot/AstrBot/astrbot/__init__.py", line 1, in <module>
    from .core.log import LogManager
  File "/www/wwwroot/AstrBot/astrbot/core/__init__.py", line 8, in <module>
    db_helper = SQLiteDatabase(DB_PATH)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 23, in __init__
    self.conn = self._get_conn(self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 29, in _get_conn
    conn = sqlite3.connect(self.db_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
(venv) ecs-user@iZ2ze6vc1a9sydwysuq7mzZ:/www/wwwroot/AstrBot$ sudo venv/bin/python3 main.py
Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 8, in <module>
    from astrbot.core.core_lifecycle import AstrBotCoreLifecycle
  File "/www/wwwroot/AstrBot/astrbot/__init__.py", line 1, in <module>
    from .core.log import LogManager
  File "/www/wwwroot/AstrBot/astrbot/core/__init__.py", line 8, in <module>
    db_helper = SQLiteDatabase(DB_PATH)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 23, in __init__
    self.conn = self._get_conn(self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 29, in _get_conn
    conn = sqlite3.connect(self.db_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
(venv) ecs-user@iZ2ze6vc1a9sydwysuq7mzZ:/www/wwwroot/AstrBot$ sudo ./venv/bin/python3 main.py
Traceback (most recent call last):
  File "/www/wwwroot/AstrBot/main.py", line 8, in <module>
    from astrbot.core.core_lifecycle import AstrBotCoreLifecycle
  File "/www/wwwroot/AstrBot/astrbot/__init__.py", line 1, in <module>
    from .core.log import LogManager
  File "/www/wwwroot/AstrBot/astrbot/core/__init__.py", line 8, in <module>
    db_helper = SQLiteDatabase(DB_PATH)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 23, in __init__
    self.conn = self._get_conn(self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/www/wwwroot/AstrBot/astrbot/core/db/sqlite.py", line 29, in _get_conn
    conn = sqlite3.connect(self.db_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file`

### 你愿意提交 PR 吗？

- [ ] 是的，我愿意提交 PR!

### Code of Conduct

- [X] 我已阅读并同意遵守该项目的 [行为准则](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)。

**Comment by Soulter** [comment]
能够成功复现，已修复
